<?php

/**
 * @file
 * Exported Custom group and fields for Sync Event to Thinkific.
 */

use Civi\Thinkific\EventCustomFieldsManager;

$mgd = [
  [
    'name' => 'CustomGroup_Sync_Event_to_Thinkific',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => EventCustomFieldsManager::CUSTOM_GROUP,
        'title' => 'Sync Event to Thinkific',
        'extends' => 'Event',
        'extends_entity_column_value' => NULL,
        'style' => 'Inline',
        'collapse_display' => TRUE,
        'help_pre' => '',
        'help_post' => '',
        'weight' => 93,
        'is_active' => TRUE,
        'is_multiple' => FALSE,
        'min_multiple' => NULL,
        'max_multiple' => NULL,
        'collapse_adv_display' => TRUE,
        'created_date' => '2025-03-06 11:38:25',
        'is_reserved' => FALSE,
        'is_public' => FALSE,
        'icon' => '',
        'extends_entity_column_id' => NULL,
        'table_name' => 'civicrm_value_lms_sync_event_to_thinkific',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Sync_Event_to_Thinkific_Sync_to_Thinkific',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Sync_Event_to_Thinkific_Sync_to_Thinkific',
        'title' => 'Sync Event to Thinkific :: Sync to Thinkific',
        'description' => NULL,
        'data_type' => 'String',
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'is_locked' => FALSE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
    ],
  ],
  [
    'name' => 'OptionGroup_Sync_Event_to_Thinkific_Sync_to_Thinkific_OptionValue_Enable_Sync_to_Thinkific',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'Sync_Event_to_Thinkific_Sync_to_Thinkific',
        'label' => 'Enable Sync to Thinkific',
        'value' => 1,
        'name' => 'Enable_Sync_to_Thinkific',
        'grouping' => NULL,
        'filter' => 0,
        'is_default' => FALSE,
        'description' => NULL,
        'is_optgroup' => FALSE,
        'is_reserved' => FALSE,
        'is_active' => TRUE,
        'icon' => NULL,
        'color' => NULL,
        'component_id' => NULL,
        'domain_id' => NULL,
        'visibility_id' => NULL,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Sync_Event_to_Thinkific_CustomField_Sync_to_Thinkific',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => EventCustomFieldsManager::CUSTOM_GROUP,
        'name' => EventCustomFieldsManager::SYNC_FIELD,
        'label' => 'Sync event to Thinkific',
        'data_type' => 'String',
        'html_type' => 'CheckBox',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 100,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'sync_to_thinkific',
        'option_group_id.name' => 'Sync_Event_to_Thinkific_Sync_to_Thinkific',
        'serialize' => 1,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Sync_Event_to_Thinkific_CustomField_Thinkific_Course_Id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => EventCustomFieldsManager::CUSTOM_GROUP,
        'name' => EventCustomFieldsManager::ID_FIELD,
        'label' => 'Thinkific course ID',
        'data_type' => 'String',
        'html_type' => 'Text',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => TRUE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 255,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'thinkific_course_id',
        'serialize' => 0,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Sync_Event_to_Thinkific_CustomField_Roles_to_Enroll_in_Thinkific_Course',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => EventCustomFieldsManager::CUSTOM_GROUP,
        'name' => EventCustomFieldsManager::ROLES_FIELD,
        'label' => 'Participant roles to enrol in Thinkific course',
        'data_type' => 'String',
        'html_type' => 'Select',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 1000,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'roles_to_enroll_in_thinkific_course',
        'serialize' => 1,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_Sync_Event_to_Thinkific_CustomField_Status_to_Enroll_in_Thinkific_Course',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => EventCustomFieldsManager::CUSTOM_GROUP,
        'name' => EventCustomFieldsManager::STATUS_FIELD,
        'label' => 'Participant status to enrol in Thinkific course',
        'data_type' => 'String',
        'html_type' => 'Select',
        'default_value' => NULL,
        'is_required' => FALSE,
        'is_searchable' => FALSE,
        'is_search_range' => FALSE,
        'help_pre' => NULL,
        'help_post' => NULL,
        'mask' => NULL,
        'attributes' => NULL,
        'javascript' => NULL,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'options_per_line' => NULL,
        'text_length' => 1000,
        'start_date_years' => NULL,
        'end_date_years' => NULL,
        'date_format' => NULL,
        'time_format' => NULL,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'status_to_enroll_in_thinkific_course',
        'serialize' => 1,
        'filter' => NULL,
        'in_selector' => FALSE,
      ],
    ],
  ],
];

return $mgd;
