name: Phpstan

on: pull_request

jobs:
  run-phpstan:

    runs-on: ubuntu-latest
    container: compucorp/civicrm-buildkit:1.3.1-php8.0

    env:
      CIVICRM_EXTENSIONS_DIR: site/web/sites/all/modules/civicrm/tools/extensions
      CIVICRM_SETTINGS_DIR: site/web/sites/default

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.CIVICRM_EXTENSIONS_DIR }}/thinkific

      - name: Run phpstan
        working-directory: ${{ env.CIVICRM_EXTENSIONS_DIR }}/thinkific
        run: ./bin/phpstan.phar analyse -c phpstan.neon
